spring.application.name=courier

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/Rwandan_Local_Courier_Service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=ls2faust

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Thymeleaf Configuration
spring.thymeleaf.cache=false

# Server port
server.port=8080
